version: '3.1'
services:
  stats-server:
    build: stat/stat-server
    image: ewm-stat
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres